### ISSUE TITLE
UNSAFE_componentWillReceiveProps

### ISSUE THREAD

**Issue by piscium2010** [jquense/react-input-message#4]
componentWillReceiveProps will be decommissioned in React 17. Would you guys have time to simply replace it with UNSAFE_componentWillReceiveProps?

ps: only 30+ start? this is an awesome library

**Comment by jquense** [comment]
I've mostly merged this library into react-formal directly so don't use it personally any more. Happy to merge and release a PR tho if you wanna send one over!

**Comment by piscium2010** [comment]
My pleasure to contribute
